### ISSUE TITLE
Difference

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [ziadOUA/zCalc#1]
What is the difference between your app and Catima, except the app name, the color and the logo?

**Comment by ziadOUA** [comment]
Hi @mondlicht-und-sterne !

Open the issue directly in the [zCard repo](https://github.com/ziadOUA/zCard), to keep things as organized as they can be.

Thanks 🙂

**Comment by ViktorKahu** [comment]
Thanks. The font does look nicer.

**Comment by mondlicht-und-sterne** [comment]
I had already read the README.md BEFORE I asked.

**Comment by ziadOUA** [comment]
(?) I told you to go and open the issue in the [zCard repo](https://github.com/ziadOUA/zCard), not to read the README, because you opened it in the wrong repo
