### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [ziadOUA/zCalc#2]
It's a nice looking app. However, how is this not an exact copy of [this](https://github.com/Darkempire78/OpenCalc) ?

**Comment by ziadOUA** [comment]
Hi @ViktorKahu !
Thanks for the compliment.

zCalc and OpenCalc are very similar, but I updated all the material icons the more recent [Material Symbols](https://fonts.google.com/icons?icon.set=Material+Symbols). I also updated the fonts & operation icons (custom made by me).
The "About" page has also been updated, and the switches of the settings page have been restored to fully follow the Material 3 guidelines (they were altered in OpenCalc).

Overall, zCalc is a more polished version of OpenCalc.

**Comment by ghost** [comment]
Thanks, the font does look nicer.

**Comment by ziadOUA** [comment]
I think that I will add in the README what has been improved (with screenshots, before & after).
