### ISSUE TITLE
New update when?

### ISSUE THREAD

**Issue by Dragonfly-30** [ziadOUA/zCalc#5]
Opencalc got update, are you going to continue it as opencalc or it'll get it's own changes and get diverted from opencalc?

**Comment by ziadOUA** [comment]
Hello @Drangonfly30,

I'm still working on the UI, because it has some severe flaws since I tried to make the buttons more legible.
Please be patient, the update will come as soon as everything is polished, tested and ready.

Thanks

**Comment by Dragonfly-30** [comment]
Sorry sorry, I'm not demanding any update, maybe I phrases the sentences wrong. Take your time. Your app is already quite solid.
